### ISSUE TITLE
[1.19.2] Server crash when player enters portal

### ISSUE THREAD

**Issue by itsdinkd** [mim1q/MineCells#25]
Server crash report: https://pastebin.com/V836B7Gu

Not much else to go off of other than the player reporting that every time he entered a specific portal by his base the server crashed.,

**Comment by mim1q** [comment]
https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric

Please try installing this mod (both on the client and server) and let me know if the problem persists!

**Comment by itsdinkd** [comment]
I use connectivity which expands packets just like XL Packets. Plus more.

**Comment by DanMeadWasTaken** [comment]
Having the same issue in single player, here is my log 

https://mclo.gs/1c54t1Q

**Comment by mim1q** [comment]
@itsdinkd I think that issue is probably related to Cardinal Components in some way. No idea how to get around it :/
@DanMeadWasTaken this is a different crash, actually. Had this reported once before - seems to only happen on Quilt, so it might have something to do with their implementation of Fabric API

**Comment by DanMeadWasTaken** [comment]
@mim1q ah- alright, sorry for any confusion, is there anything i can do on my end? I'd like to use the mod, but don't wanna crash again lol - pretty much only using quilt bc one single mod which is quilt only and no fabric alternative to it.

**Comment by mim1q** [comment]
@DanMeadWasTaken I released version 1.3.4 today - please check out if it changes anything

**Comment by DanMeadWasTaken** [comment]
Well, this seems to fix it! thank you so much

**Comment by RCertainty** [comment]
Unfortunately, after the server updated to 1.3.4 version of mine cells, the server would still crash as soon as anyone entered a prison gate (The mod pack the server is using is Medieval MC (Fabric))

**Comment by mim1q** [comment]
https://github.com/iPortalTeam/ImmersivePortalsMod/pull/705
This seems to be a possible solution, I'll try that out

**Comment by mim1q** [comment]
@RCertainty I just released 1.3.5. Let me know if that fixes the crash!

**Comment by mim1q** [comment]
Another player has confirmed that this issue should no longer be happening as of 1.3.5! Closing, let me know if the issue still persists in any way :)
